Repository plonegovbr/brasil.gov.agenda, pull requests merged in 2018-09, with the labels that each got.

#141 Update webpack
  CHANGES.rst
  buildout.cfg
  webpack/.babelrc
  webpack/package.json
Labels: ready

#143 Fix the title on AgendaDiaria view in case the name of the person charge changes
  CHANGES.rst
  src/brasil/gov/agenda/browser/agendadiaria.py
  src/brasil/gov/agenda/browser/templates/agendadiariaview.pt
Labels: 2.x, in progress

#144 Simplify agenda view
  CHANGES.rst
  buildout.cfg
  src/brasil/gov/agenda/browser/agenda.py
  src/brasil/gov/agenda/browser/mixin.py
  src/brasil/gov/agenda/browser/templates/agenda_macros.pt
  src/brasil/gov/agenda/browser/templates/agendadiariaview.pt
  src/brasil/gov/agenda/profiles/default/metadata.xml
  src/brasil/gov/agenda/tests/test_setup.py
  src/brasil/gov/agenda/tests/test_upgrades.py
  src/brasil/gov/agenda/tiles/agenda.pt
  src/brasil/gov/agenda/tiles/agenda.py
  src/brasil/gov/agenda/upgrades/configure.zcml
  src/brasil/gov/agenda/upgrades/v4103/__init__.py
  src/brasil/gov/agenda/upgrades/v4103/configure.zcml
  webpack/app/js/agenda.js
  webpack/app/js/datepicker.js
  webpack/app/js/tile.js
  webpack/app/scss/_datepicker.scss
  webpack/app/scss/_tile.scss
Labels: in progress

#146 Fix daypicker URL
  src/brasil/gov/agenda/browser/mixin.py
  src/brasil/gov/agenda/browser/templates/agenda_macros.pt
  webpack/app/js/datepicker.js
  webpack/app/js/tile.js
Labels: ready
