Repository plonegovbr/brasil.gov.agenda, pull requests merged in 2018-06, with the labels that each got.

#93 Fixes on agenda view
  webpack/app/js/agenda.js
  webpack/app/js/datepicker.js
  webpack/app/js/tile.js
Labels: ready

#79 Remove dependency on five.grok
  CHANGES.rst
  setup.py
  src/brasil/gov/agenda/browser/__init__.py
  src/brasil/gov/agenda/browser/agenda.py
  src/brasil/gov/agenda/browser/agendadiaria.py
  src/brasil/gov/agenda/browser/compromisso.py
  src/brasil/gov/agenda/browser/configure.zcml
  src/brasil/gov/agenda/browser/ics.py
  src/brasil/gov/agenda/browser/vcs.py
  src/brasil/gov/agenda/configure.zcml
  src/brasil/gov/agenda/tests/test_agendadiaria.py
  src/brasil/gov/agenda/tests/test_compromisso.py
  src/brasil/gov/agenda/tests/test_setup.py
  src/brasil/gov/agenda/tiles/agenda.py
Labels: enhancement, help wanted, in progress

#74 Python 3 compatibility
  CHANGES.rst
  setup.py
  src/brasil/gov/agenda/browser/ics.py
  src/brasil/gov/agenda/browser/vcs.py
  src/brasil/gov/agenda/utils.py
Labels: enhancement, help wanted, in progress

#91 Remove upgrade steps from branch 1.x
  CHANGES.rst
  README.rst
  src/brasil/gov/agenda/config.py
  src/brasil/gov/agenda/profiles.zcml
  src/brasil/gov/agenda/profiles/default/metadata.xml
  src/brasil/gov/agenda/setuphandlers.py
  src/brasil/gov/agenda/tests/test_setup.py
  src/brasil/gov/agenda/tests/test_upgrades.py
  src/brasil/gov/agenda/upgrades/configure.zcml
  src/brasil/gov/agenda/upgrades/v2000/__init__.py
  src/brasil/gov/agenda/upgrades/v2000/configure.zcml
  src/brasil/gov/agenda/upgrades/v2000/handler.py
  src/brasil/gov/agenda/upgrades/v2000/profile/metadata.xml
  src/brasil/gov/agenda/upgrades/v3000/__init__.py
  src/brasil/gov/agenda/upgrades/v3000/configure.zcml
  src/brasil/gov/agenda/upgrades/v3000/handler.py
  src/brasil/gov/agenda/upgrades/v3000/profile/catalog.xml
  src/brasil/gov/agenda/upgrades/v3000/profile/metadata.xml
  src/brasil/gov/agenda/upgrades/v4000/__init__.py
  src/brasil/gov/agenda/upgrades/v4000/configure.zcml
  src/brasil/gov/agenda/upgrades/v4000/handler.py
  src/brasil/gov/agenda/upgrades/v4000/profile/registry.xml
  src/brasil/gov/agenda/upgrades/v4001/__init__.py
  src/brasil/gov/agenda/upgrades/v4001/configure.zcml
  src/brasil/gov/agenda/upgrades/v4001/handler.py
  src/brasil/gov/agenda/upgrades/v4002/__init__.py
  src/brasil/gov/agenda/upgrades/v4002/configure.zcml
  src/brasil/gov/agenda/upgrades/v4002/handler.py
  src/brasil/gov/agenda/upgrades/v4003/__init__.py
  src/brasil/gov/agenda/upgrades/v4003/configure.zcml
  src/brasil/gov/agenda/upgrades/v4100/__init__.py
  src/brasil/gov/agenda/upgrades/v4100/configure.zcml
Labels: enhancement, in progress

#119 Highlight calendar events
  CHANGES.rst
  src/brasil/gov/agenda/browser/agenda.py
  src/brasil/gov/agenda/tests/test_compromisso.robot
  webpack/app/js/datepicker.js
  webpack/app/scss/_datepicker.scss
Labels: ready
